### PR TITLE
Fix php 7.4 pipelines

### PR DESCRIPTION
**Pull request by eerison**
https://github.com/markitosgv/JWTRefreshTokenBundle/actions/runs/3355047594/jobs/5559029249

### CODE REVIEW

**Comment by maxhelias** [comment]
I think we should bump the version of doctrine/mongodb-odm to `^2.2` instand of `^2.0` which no longer has the package

**Comment by eerison** [comment]
even if I bump to `"doctrine/mongodb-odm": "^2.2",`, composer ask me to add `"ocramius/package-versions": true`

**Comment by eerison** [comment]
you are correct! I missed to add `--prefer-stable --prefer-lowest --prefer-dist`

**Review by maxhelias — APPROVED** [review]

**Comment by mbabker** [comment]
You should update the conflict as well otherwise the minimum version being tested in dev doesn't match up with the minimum version that can be installed in production.

**Comment by eerison** [comment]
> You should update the conflict as well otherwise the minimum version being tested in dev doesn't match up with the minimum version that can be installed in production.

Ahhh I got it know :D 

because it's only in require-dev, yeah it's needed for conflicts as well!

**Review by mbabker — APPROVED** [review]

**Comment by shakaran** [comment]
@mbabker could be this merged to master? Thanks

**Comment by thomaspicquet** [comment]
@markitosgv let us know if you need extra help with this bundle so PRs can get merged faster

**Pull request merged**
