### PR TITLE
Add doctrine/common 3+ support, close #200.

### LINKED ISSUE #200: Error in RefreshTokenManager - Support for doctrine/common +3.0
Since Doctrine Common 3.0, Common was split into smaller packages.

Actually in [RefreshTokenManager](https://github.com/markitosgv/JWTRefreshTokenBundle/blob/master/Doctrine/RefreshTokenManager.php) you inject `Doctrine\Common\Persistence\ObjectManager` in constructor.

Since Doctrine Common 3.0, `Doctrine\Common\Persistence\ObjectManager` became `Doctrine\Persistence\ObjectManager`.

### PR DESCRIPTION
**Pull request by Invis1bleReborn**
This PR should fix #200

### CODE REVIEW

**Comment by Majkl578** [comment]
Please also add explicit dependency on `"doctrine/common": `"^3"` to `composer.json`.

**Comment by Invis1bleReborn** [comment]
@markitosgv what is wrong with this build? Maybe you can restart it?

**Comment by Invis1bleReborn** [comment]
@Majkl578 I don't think that it is a good idea, because doctrine/common is not required by [gesdinet/jwt-refresh-token-bundle](https://github.com/markitosgv/JWTRefreshTokenBundle/blob/master/composer.json)

**Comment by Majkl578** [comment]
It is since it's used by `Doctrine/RefreshTokenManager.php` - missing dependency has just caused our downstream app issue during doctrine/common upgrade.

**Comment by Majkl578** [comment]
Ah I see, sorry, I meant `doctrine/persistence` dependency, not `doctrine/common`.

**Pull request closed without merging**
